### ISSUE TITLE
ウインドウサイズによってはカラム内の要素が見切れる

### ISSUE THREAD

**Issue by munierujp** [blue0513/slackdeck-proto#28]
`settings.json`で`width`を`large-tab`にしても、ウインドウサイズによってはこのようにカラム内の要素が見切れてしまいます。

![スクリーンショット 2019-06-23 22 57 35](https://user-images.githubusercontent.com/20086673/59977317-c88c7b80-960a-11e9-989f-50e77da4612d.png)

おそらく、CSSで`.large-tab`の`width`を`30%`と相対値にしていることが原因かと思われます。
対策として、`800px`（数値は適当です）のように絶対値にするか、`min-width`で最小値も指定するといいかと思います。

`style.css`の該当箇所：

```css
.large-tab{
    display: inline-block;
    height: 100%;
    width: 30%;
    border: solid;
    border-width: thin;
}
```

## 参考
`.large-tab`の`width`を`800px`、`.small-tab`の`width`を`220px`にすると次のような感じになります。

![スクリーンショット 2019-06-23 23 10 07](https://user-images.githubusercontent.com/20086673/59977462-32f1eb80-960c-11e9-844a-e3081a932aa2.png)
